<?php
/** @AUTHOR: 			Anoop Singh* @TIMESTAMP:		27-April-2010* @EMAIL:			anoop.immortal@gmail.com* @DESCRIPTION: 	This file is used to create image with random numbers on different Cells And do the login validation.					For this i have followed certain steps:						1) Create local variables for loop to be select random numbers ("numberSequence", "numberDisplaySequence").						2) Create mapImage array for matrix.						3) Create blank image of 139 X 129.						4) Create color code with "imagecolorallocate".						5) DRAW horizontal lines on image "imageline".						6) DRAW vertical lines on image "imageline".						7) Fill background as white to the number "imagefilledrectangle" "imagefttext";						8) Store Number Information in session.						9)  Save image with name as session ID "imagepng".					This file creates the number cell grid for secure password image used in passwd_square.php.**/
	/// -- Starts Session Request --	@session_start();	header("Cache-Control: no-cache, must-revalidate");	header("Pragma: no-cache");
	/// -- Output image to the browser --	header('Content-Type: image/gif');
	/// -- Holds the folder path store the image	$folderPath = "img/gridImages/";		if(isset($_SESSION["fileName"]))	{		@unlink($folderPath.$_SESSION["fileName"]);	}	/// -- Array to hold numbers to display on image --	$numberSequence=array();	/// -- Array to hold random position to display numbers on image --	$numberDisplaySequence=array();
	$total=10;	$min=0;	$max=9;
	/// -- variable helps to render grid with random values.	$totalCellShuffle=10; 	$minCell=1;	$maxCell=25;
	/// -- Holds the session result.	$result=array();
	/// -- Array to mapping matrix for number ploting --	$mapImage=array(		1 =>"6,5,25,24",		2 =>"32,5,51,24",		3 =>"58,5,77,24",		4 =>"84,5,103,24",		5 =>"110,5,129,24",		6 =>"6,31,25,50",		7 =>"32,31,51,50",		8 =>"58,31,77,50",		9 =>"84,31,103,50",		10 =>"110,31,129,50",		11 =>"6,56,25,75",		12 =>"32,56,51,75",		13 =>"58,56,77,75",		14 =>"84,56,103,75",		15 =>"110,56,129,75",		16 =>"6,81,25,100",		17 =>"32,81,51,100",		18 =>"58,81,77,100",		19 =>"84,81,103,100",		20 =>"110,81,129,100",		21 =>"6,106,25,125",		22 =>"32,106,51,125",		23 =>"58,106,77,125",		24 =>"84,106,103,125",		25 =>"110,106,129,125"	);
	/// -- Create a 139x129 image --	$im = imagecreatetruecolor(139, 129);	$defaultColor = imagecolorallocate($im, 0x69,0xdc,0x9a);	$lineColor= imagecolorallocate($im, 0x28,0xaa,0x60);	$digitColor = imagecolorallocate($im, 0xFF, 0xFF, 0xFF);	$digitBgColor = imagecolorallocate($im, 0x00, 0x00, 0x00);	///  -- Make the background transparent--	imagecolortransparent($im, $defaultColor);	imagefilledrectangle($im, 0, 0, 139, 129, $defaultColor);	/// -- Horizontal lines --	imageline($im, 1, 28,130,28, $lineColor);	imageline($im, 1,54,130,54, $lineColor);	imageline($im, 1,78,130,78, $lineColor);	imageline($im, 1,102,130,102, $lineColor);
	/// -- Vertical lines lines --	imageline($im, 28,1,28,126, $lineColor);	imageline($im, 54,1,54,126, $lineColor);	imageline($im, 78,1,78,126, $lineColor);	imageline($im, 106,1,106,126, $lineColor);
	/// -- Path to our ttf font file --	$font_file = 'font/arial.ttf';  	/// -- Create random array of digit from 0-9 to show digit	while (count($numberSequence) < $total ) {		$r = mt_rand($min,$max);		if ( !in_array($r,$numberSequence) ) {			$numberSequence[] = $r;		}	}
	/// -- Shuffle the cell id for 0-9 deigits --	while (count($numberDisplaySequence) < $totalCellShuffle ) {		$s = mt_rand($minCell,$maxCell);		if ( !in_array($s,$numberDisplaySequence) ) {			$numberDisplaySequence[]= $s;		}	}
	/// -- Pick mapImage value from $numberDisplaySequence array and fill number --	/// -- On random location using $numberSequence[$key] --	foreach($numberDisplaySequence as $key => $value)	{	    $valueCoordinates=explode(",",$mapImage[$value]);	    /// -- Set the border and fill colors --	    imagefilledrectangle($im, $valueCoordinates[0]-1, $valueCoordinates[1]+1, $valueCoordinates[2]-1, $valueCoordinates[3]-1, $digitColor);		/// -- Draw the text '1,2,3,...9' using font size 12 --	    imagefttext($im,12, 0,$valueCoordinates[0]+4, $valueCoordinates[3]-2, $digitBgColor, $font_file, $numberSequence[$key]);	    $result[$value]=$numberSequence[$key];	}
	/// -- Store Filename as a random number sequence --	$fileName=implode($numberDisplaySequence,"");
	/// -- Store Result to session on further use --	$_SESSION["result"]=$result;
	/// -- Store Filename to session on further use --	$_SESSION["fileName"]=$fileName.".gif";	$completeFilePath = $folderPath.$fileName.".gif";
	/// -- Save Image with file name as a random number --	imagegif($im, $completeFilePath);	/// -- Change the file rights to remove it later.	@chmod($completeFilePath, 0777);	/// -- read the image file so that grid image src can get a valid image.	@readfile($completeFilePath);
?>

